# Generated by Django 4.0.3 on 2022-06-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyCreate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='My_Family',
            new_name='My_Room',
        ),
        migrations.RenameField(
            model_name='my_room',
            old_name='name_room_family',
            new_name='name_room',
        ),
        migrations.RemoveField(
            model_name='my_users',
            name='family',
        ),
        migrations.AddField(
            model_name='my_users',
            name='room',
            field=models.ManyToManyField(to='FamilyCreate.my_room'),
        ),
        migrations.AlterModelTable(
            name='my_room',
            table='my_room',
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
    ]
