# Generated by Django 4.0.3 on 2022-06-11 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyCreate', '0002_rename_my_family_my_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_user', models.IntegerField()),
                ('id_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FamilyCreate.my_roles')),
                ('id_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FamilyCreate.my_room')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_room',
            },
        ),
    ]
