# Generated by Django 4.0.3 on 2022-06-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyCreate', '0003_users_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_users',
            name='room',
        ),
        migrations.AlterField(
            model_name='my_room',
            name='name_room',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
