# Generated by Django 4.0.3 on 2022-06-18 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyCreate', '0005_task_id_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id_room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='FamilyCreate.my_room'),
        ),
    ]
