# Generated by Django 4.0.3 on 2022-06-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyCreate', '0007_taken_user_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
